// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import ()

type Resource struct {
	ID          interface{}
	Name        interface{}
	ProjectID   interface{}
	Description interface{}
	Tags        interface{}
	Type        int64
	Locality    interface{}
	JsonData    interface{}
}
