// Code generated by "stringer -type=Type -linecomment -trimprefix=Type"; DO NOT EDIT.

package resource

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeProject-0]
	_ = x[TypeIAMApplication-1]
	_ = x[TypeCockpit-2]
	_ = x[TypeFunctionNamespace-3]
	_ = x[TypeFunction-4]
	_ = x[TypeContainerNamespace-5]
	_ = x[TypeContainer-6]
	_ = x[TypeRegistryNamespace-7]
	_ = x[TypeRdbInstance-8]
	_ = x[TypeKapsuleCluster-9]
	_ = x[NumberOfResourceTypes-10]
}

const _Type_name = "ProjectIAM ApplicationCockpitFunction NamespaceFunctionContainer NamespaceContainerRegistry NamespaceRDB InstanceKapsule ClusterNumberOfResourceTypes"

var _Type_index = [...]uint8{0, 7, 22, 29, 47, 55, 74, 83, 101, 113, 128, 149}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
