name: quality

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
    contents: read

defaults:
  run:
    shell: bash

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v4
      with:
        go-version: '^1.21'

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.55
        args: --timeout 5m
    
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v4
      with:
        go-version: '^1.21'
        cache: false

    - name: go test
      run: go test -v ./...
