name: temp

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
    contents: read

defaults:
  run:
    shell: bash

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - uses: bemble/sync-readme@v1.0.0
        with:
          pass: ${{ secrets.DOCKERHUB_TOKEN }}
          description: true
